"""Add TokenBlocklist

Revision ID: 1d993b915000
Revises: 34772beab9af
Create Date: 2026-09-08 22:49:57.373630
"""
from alembic import op
import sqlalchemy as sa

revision = '1d993b915000'
down_revision = '34772beab9af'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_blocklist_expires_at', 'token_blocklist', ['expires_at'], unique=False)
    op.create_index('ix_token_blocklist_jti', 'token_blocklist', ['jti'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blocklist_jti', table_name='token_blocklist')
    op.drop_index('ix_token_blocklist_expires_at', table_name='token_blocklist')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
