"""Add is_deleted to reports

Revision ID: 26b39af587cb
Revises: 7d8b2ee65f50
Create Date: 2026-09-09 11:42:28.467425
"""
from alembic import op
import sqlalchemy as sa

revision = '26b39af587cb'
down_revision = '7d8b2ee65f50'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_reports_is_deleted'), 'reports', ['is_deleted'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_is_deleted'), table_name='reports')
    op.drop_column('reports', 'is_deleted')
    # ### end Alembic commands ###
