"""CorrectiveActionStatus Enum

Revision ID: 2b3a479e42e2
Revises: 4af5a0609346
Create Date: 2026-09-08 23:09:01.860876
"""
from alembic import op
import sqlalchemy as sa

revision = '2b3a479e42e2'
down_revision = '4af5a0609346'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrective_actions', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'VERIFICATION_PENDING', 'COMPLETED', 'CLOSED', 'CANCELLED', name='correctiveactionstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrective_actions', 'status',
               existing_type=sa.Enum('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'VERIFICATION_PENDING', 'COMPLETED', 'CLOSED', 'CANCELLED', name='correctiveactionstatus', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    # ### end Alembic commands ###
