"""Phase 1 backend completion

Revision ID: 34772beab9af
Revises: ff9d8e85b44d
Create Date: 2026-09-08 22:11:05.247440
"""
from alembic import op
import sqlalchemy as sa

revision = '34772beab9af'
down_revision = 'ff9d8e85b44d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('site_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_foreign_key(None, 'users', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_column('users', 'site_id')
    # ### end Alembic commands ###
