"""Add LSRMatch

Revision ID: 4af5a0609346
Revises: 1d993b915000
Create Date: 2026-09-08 22:58:43.560165
"""
from alembic import op
import sqlalchemy as sa

revision = '4af5a0609346'
down_revision = '1d993b915000'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lsr_matches',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['report_analyses.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['life_saving_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lsr_matches_analysis_id', 'lsr_matches', ['analysis_id'], unique=False)
    op.create_index('ix_lsr_matches_rule_id', 'lsr_matches', ['rule_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lsr_matches_rule_id', table_name='lsr_matches')
    op.drop_index('ix_lsr_matches_analysis_id', table_name='lsr_matches')
    op.drop_table('lsr_matches')
    # ### end Alembic commands ###
