"""update_corrective_action_status_enum

Revision ID: 7d8b2ee65f50
Revises: 8d40e97e7ba2
Create Date: 2026-09-09 11:03:26.715280
"""
from alembic import op
import sqlalchemy as sa

revision = '7d8b2ee65f50'
down_revision = '8d40e97e7ba2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrective_actions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'IN_PROGRESS', 'VERIFICATION_REQUIRED', 'VERIFIED', 'CLOSED', 'REJECTED', 'CANCELLED', name='correctiveactionstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corrective_actions', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'IN_PROGRESS', 'VERIFICATION_REQUIRED', 'VERIFIED', 'CLOSED', 'REJECTED', 'CANCELLED', name='correctiveactionstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    # ### end Alembic commands ###
