"""Add ModelVersion

Revision ID: 8d40e97e7ba2
Revises: 2b3a479e42e2
Create Date: 2026-09-08 23:12:44.293014
"""
from alembic import op
import sqlalchemy as sa

revision = '8d40e97e7ba2'
down_revision = '2b3a479e42e2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
