"""Add soft delete and idempotency to reports, add indexes

Revision ID: 996a275a690d
Revises: 26b39af587cb
Create Date: 2026-09-09 13:53:48.616215
"""
from alembic import op
import sqlalchemy as sa

revision = '996a275a690d'
down_revision = '26b39af587cb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_report_analyses_created', 'report_analyses', ['created_at'], unique=False)
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.add_column('reports', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_reports_idempotency_key'), 'reports', ['idempotency_key'], unique=False)
    op.create_unique_constraint('uq_report_site_idempotency', 'reports', ['site_id', 'idempotency_key'])
    op.create_foreign_key(None, 'reports', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint('uq_report_site_idempotency', 'reports', type_='unique')
    op.drop_index(op.f('ix_reports_idempotency_key'), table_name='reports')
    op.drop_column('reports', 'idempotency_key')
    op.drop_column('reports', 'deleted_by')
    op.drop_column('reports', 'deleted_at')
    op.drop_index('ix_report_analyses_created', table_name='report_analyses')
    # ### end Alembic commands ###
