"""Add causal intelligence and new fields to report_analyses

Revision ID: ff9d8e85b44d
Revises: 20260904_0005
Create Date: 2026-09-08 21:28:10.149976
"""
from alembic import op
import sqlalchemy as sa

revision = 'ff9d8e85b44d'
down_revision = '20260904_0005'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_analyses', sa.Column('evidence_sentences', sa.JSON(), nullable=True))
    op.add_column('report_analyses', sa.Column('safety_graph', sa.JSON(), nullable=True))
    op.add_column('report_analyses', sa.Column('causal_chains', sa.JSON(), nullable=True))
    op.add_column('report_analyses', sa.Column('reasoning_summary', sa.Text(), nullable=True))
    op.add_column('report_analyses', sa.Column('precursor_priority_used', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_analyses', 'precursor_priority_used')
    op.drop_column('report_analyses', 'reasoning_summary')
    op.drop_column('report_analyses', 'causal_chains')
    op.drop_column('report_analyses', 'safety_graph')
    op.drop_column('report_analyses', 'evidence_sentences')
    # ### end Alembic commands ###
